### ISSUE TITLE
Weird lines in left column

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/Keira3#1025]
![image](https://user-images.githubusercontent.com/24550914/103321406-cd20c400-4a39-11eb-9c88-646f4338da76.png)

Only happens in Other Loots

**Comment by FrancescoBorzi** [comment]
hehe this is intended :D I'm a terrible UI designer 🤦‍♂️

**Comment by Kitzunu** [comment]
But then the issue is still relevant since it doesnt happen in any other bar

**Comment by FrancescoBorzi** [comment]
@Kitzunu it's not an "issue". I added these bars on purpose, it doesn't happen in other categories because I didn't put it there.

The reason is: in other categories all the editors are related to each other, while "fishing loot" and "mail loot" have nothing in common apart of being both loot (just like "creature loot").

So this is not a bug. If you think this is ugly and we should remove it, it is of course open for discussion! I just wanted to point that it is not a bug.

**Comment by Kitzunu** [comment]
Yea my personal opinion is that either it is done everywhere or nowhere. As for esthetics, I think both are valid options

**Comment by FrancescoBorzi** [comment]
@Kitzunu the thing is, as soon as you select one of them, you have a sub-category composed by the "Select xxx loot" and the "xxx loot". I personally find it useful to not mix different loots together

**Comment by Kitzunu** [comment]
Ah
