### ISSUE TITLE
Editing spawns tries to delete/replace instead of change existing values.

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/Keira3#1446]
```sql
DELETE FROM `creature` WHERE (`id` = 9318) AND (`guid` IN (5874));
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES
(5874, 9318, 0, 0, 0, 1, 1, 8509, 0, -6449.05, -1430.19, 145.087, 3.6814, 60, 10, 0, 2488, 0, 1, 0, 0, 0, '', 0);
```

![Desktop 10-09-2021 10-44-49-316](https://user-images.githubusercontent.com/61194190/132834880-d61766f0-8be7-4a29-a5d1-c5834bd3774c.png)

This edit from 500 to 60 should just change 500 to 60, not delete the existing record and spit out a near-identical record with the change.

**Comment by FrancescoBorzi** [comment]
@JamesGent this is intended, I know it's not optimal but at the moment we have 2 kinds of entities:

- single-row (e.g. `creature_template`)
- multi-row (e.g. `creature_loot_template`)

 when modifying an existing entity, for single-row entities we use `UPDATE` while for multi-row ones we use `DELETE`/`INSERT`. The reason is simply it is much easier to handle code-wise. Not perfect, but works fine.

More info about Keira3 internals:

https://www.azerothcore.org/wiki/keira3-internals
