### ISSUE TITLE
SmartScript Cast Spell when die

### ISSUE THREAD

**Issue by admdbreno** [azerothcore/Keira3#2346]
Good morning friends, I have a problem, I hope someone can help me...
Next: I created 3 npcs "Test1Ally, Test2Horde, npc test", so far so good.
I also created a spell where the npc "Test2Horde" will summon the "npc test" to help him for 30 seconds; my intention is: whenever the "npc test" dies, he casts the spell "drain mana: 58770" against the summoner who called him "Test2Horde", I am not able to do that...
OBS: the only way I got it was using the following:
Event= 6 - death
Action= 110 - remove_power
Target= 23 - owner_or_summoner
PowerType= 0 - mana
PowerValue= 10000
however this form inflicts a problem... if the mob's mana is below 10000 and the "npc test" dies and triggers the script, the interpreter instead of leaving the moob's mana with 0, it fills the moob's mana bar moob. Can anyone help me with this? I will send prints to help in solving the problem.
![WoWScrnShot_073023_083552](https://github.com/azerothcore/Keira3/assets/33205929/7a2a1fb8-7adc-4438-8799-4abbfc6f1fae)
![WoWScrnShot_073023_084011](https://github.com/azerothcore/Keira3/assets/33205929/4c8a6f9a-0558-480d-bd5c-dc641f2449d4)
![Keira3 30_07_2023 08_32_51](https://github.com/azerothcore/Keira3/assets/33205929/e8ff9651-ec39-415e-963b-3ef4614ea3d5)

@Helias

**Comment by The-GhostRider** [comment]
> Good morning friends, I have a problem,

Hi @admdbreno you could try to do this one, if you haven't try it yet..
![image](https://github.com/azerothcore/Keira3/assets/1884642/9432ba14-796b-4097-b567-f64d807f47c2)

I know, theoretically, you'd be right. The combination you made should work, but for some reason, certain combinations of "Events, Actions, and Targets" don't interact correctly with each other. So, sometimes you have to try "Other" solutions, and other times, you might even need to be "Creative" to make certain things work.

Anyway, I can tell you that some functions don't work very well with the 'Death' event. This is because when NPCs are 'Dead,' there are scripts that prevent them from interacting with some functions. So, keep in mind that this could also be the issue.

In case my suggestion doesn't work, a "Creative" way to make it work could be:
**[You do this on the Npc Test SAI]:**
![image](https://github.com/azerothcore/Keira3/assets/1884642/6a088fdf-1017-4f88-aa37-463c4acfcd97)

**[You do this on the Test2Horde SAI]:**
![image](https://github.com/azerothcore/Keira3/assets/1884642/bffd0f45-6d69-4bbe-82ca-4d71c57f38eb)

**Comment by The-GhostRider** [comment]
And btw, you wrote:
![image](https://github.com/azerothcore/Keira3/assets/1884642/8e991225-2078-40f3-b32b-c3679543a7e1)

But in your script there is no "Cast of spell" did you write it wrong or am I missing something?
