### ISSUE TITLE
Creature Text Editor Issues

### ISSUE THREAD

**Issue by Gultask** [azerothcore/Keira3#3008]
There's 2 issues with the creature text editor.

### Row Selection
When selecting a row, it seems to select by ID, regardless of GroupID, making it hard to select rows which include more than one group of texts. For example, Nat Pagle (20344) has 23 rows with all unique GroupIDs but with ID all 0, so when selecting one row, it'll be impossible to edit.

Both GroupID and ID are primary keys. and only one row can be edited at a time.

![image](https://github.com/azerothcore/Keira3/assets/100873791/965d17ae-e564-44f7-a060-3253d50ea403)

### Default Values

This one's easier (and more of a suggestion), when creating a new row, some fields should be already entered by default. Although it's not explicit in the table, probability is nearly always 100 and the type should be 12, since that's the most common value.

**Comment by FrancescoBorzi** [comment]
@Instantium can you please have a look at this?

**Comment by Instantium** [comment]
Gultask is correct. Only the ID is used and not the ID and groupID. I can fix this.

@FrancescoBorzi just to check with you: 
I am using the ```MultiRowEditorService``` but I would need something like the ```MultiRowComplexKeyEditorService``` but for a complex secondary key. AFAIK there is no such Service, so I would add one. Ok with you?

I am also on board with adding default values.
Also I will remove creatureID since it is always the same anyway and never shown in other similar pages.

**Comment by FrancescoBorzi** [comment]
> Gultask is correct. Only the ID is used and not the ID and groupID. I can fix this.
> 
> @FrancescoBorzi just to check with you: I am using the `MultiRowEditorService` but I would need something like the `MultiRowComplexKeyEditorService` but for a complex secondary key. AFAIK there is no such Service, so I would add one. Ok with you?
> 
> I am also on board with adding default values. Also I will remove creatureID since it is always the same anyway and never shown in other similar pages.

@Instantium yes, what you said seems correct
