### ISSUE TITLE
[Request][Feautere] Multiply selection in *_loot, npc_vendor, npc_trainer tables

### ISSUE THREAD

**Issue by wlasser** [azerothcore/Keira3#638]
Hello there.
I think - this is be very usefull, when you can with checkboxes select more than one item in that pages of view in Keira3. And maybe add button "delete_all". But with this you must implement one more usefull feature: somethink like local history of changes, with log output for session or all work-time.

**Comment by Yehonal** [comment]
@Helias @FrancescoBorzi you could create a simple log file where storing the runned queries (IDK if you already have it)

So, when you delete something you can first generate a [commented] INSERT INTO query. In this way anyone can restore the changes. The same for the updates. It's pretty easy to generate the "

**Comment by Helias** [comment]
similar to https://github.com/azerothcore/Keira3/issues/1086, https://github.com/azerothcore/Keira3/issues/2918 and point 2 of https://github.com/azerothcore/Keira3/issues/401
I am closing this as duplicate, I know that this issue is older than the other ones but I am trying to cleaning up a bit the old issues
