### ISSUE TITLE
Feature Request Factions, Editing, Adding, Altering tables

### ISSUE THREAD

**Issue by Chromie-WoW** [azerothcore/Keira3#732]
Although people would have to use a DBC editor to export their faction.dbc to csv or directly into database. It would be amazing to be able to see, edit, and add factions. Currently that i have found, there is no system out there that does faction editing, let alone explains it well. When there is so many parent > parent > child faction setups like Classic > Horde > Town and many more with multiple parents. No clear explanations of parent mods, flags and more. 

Being able to make/choose a faction, choose its parent / make a new parent, edit values, change mods, allowing it to always display in reputation tab or hidden and sooo much more.

Being able to selection a faction and be able to see ALL the factions associated with it right there without searching through them all, so you know, 20, undead, is friendly with X and enemies with X and so forth.

A disclaimer up top of the faction page could tell people to make sure to export/import Faction.dbc Faction_template.dbc and factiongroup.dbc to database as "these names" so they can be read and edited.

**Comment by Helias** [comment]
This is interesting, I don't know if Keira3 will edit DBC too, I hope so, but personally now is not the time to do that, I am personally waiting to have this https://github.com/azerothcore/azerothcore-wotlk/pull/3002
and more free time :sweat_smile:

**Comment by Chromie-WoW** [comment]
It doesn't have to edit dbc. If you use wdbx, theres an export to DB. I do almost all my dbc work via db then import it back to wdbx. So by exporting the faction tables to your db, kiera3 can edit them, then wdbx import it back

**Comment by Helias** [comment]
You're right, we can edit the factions from the database because they are already present as SQL table in the DB.
Anyway, for now we focused on improving the current editors, I don't know when we will add more editors.

**Comment by Helias** [comment]
I am closing this because I would not implement something that relies on 3rd tools like WDBX, moreover, it is unmaintained and not cross-platform.
Ideally, I would implement a DBC editor in Keira3 that allows to make the same conversions in CSV/SQL, I am closing this feature request but I'll keep in mind the idea of implementing client-editor tools in Keira3.

We have some porting of stormlib and dbc through https://github.com/sebyx07/wow-dbcfile-node/tree/main and https://github.com/sebyx07/stormlib-node  , we could in the future implement them
